### PR TITLE
fix: loading spinner still showing after closing popup for redirect payment methods

### PR DESCRIPTION
**Pull request by RonanFabricante**
waave loading icon fix

### CODE REVIEW

**Comment by paul-gr4vy** [comment]
Which environment has this been tested on?

Also, we probably don't want to introduce that additional console logging.

**Review by paul-gr4vy — CHANGES_REQUESTED** [review]
I don't think we want to be throwing an error if the user closes the redirect popup because it results in an error message on the checkout page saying something along the lines of "an error has occurred on the server".

We should remove the excess console logging before merging too.

**Comment by paul-gr4vy** [comment]
I don't think this is the correct fix. If this fix solves the problem, then it looks to me like the reason the spinner is still showing after closing the popup is because the call to `This.customPlaceOrder` has failed inside `onBeforeTransaction`, which means that the `externalIdentifier` also isn't being set properly for the transaction.

I think we need to find out why `This.customPlaceOrder` is throwing an exception and fix that. We should also prevent the popup from opening at all if `This.customPlaceOrder` fails because the Gr4vy transaction won't have the right External Identifier.

**Comment by RonanFabricante** [comment]
"I don't think this is the correct fix. If this fix solves the problem, then it looks to me like the reason the spinner is still showing after closing the popup is because the call to `This.customPlaceOrder` has failed inside `onBeforeTransaction`, which means that the `externalIdentifier` also isn't being set properly for the transaction.
 
I think we need to find out why `This.customPlaceOrder` is throwing an exception and fix that. We should also prevent the popup from opening at all if `This.customPlaceOrder` fails because the Gr4vy transaction won't have the right External Identifier."

@paul-gr4vy customPlaceOrder is not throwing an exception at all. In fact, the logic of stopping the screen loader is already supported in the function if placing an order fails.

**Comment by paul-gr4vy** [comment]
> @paul-gr4vy customPlaceOrder is not throwing an exception at all. In fact, the logic of stopping the screen loader is already supported in the function if placing an order fails.

The original PR relied on `customPlaceOrder()` failing to work, so I'm suspicious that it's no longer failing. However, if it's not throwing an exception, then I think we should move stopLoader() to the end of [this function](https://github.com/gr4vy/gr4vy-magento/blob/378bbe2e56d2bda265857a7f8f2c99550309e70a/view/frontend/web/js/view/payment/method-renderer/gr4vy-method.js#L195C22-L195C22).

**Review by paul-gr4vy — APPROVED** [review]

**Pull request merged**
